apiVersion: v1
kind: Pod
metadata:
  name: redpanda
spec:
  containers:
  - name: redpanda
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.11
    command: [rpk]
    args:
      - redpanda
      - start
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:9093
      - --smp=1
      - --memory=1G
      - --mode=dev-container
      - --default-log-level=debug
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - rpk cluster health | grep 'Healthy:.*true'
      initialDelaySeconds: 1
      periodSeconds: 1
