{{ $name := .Values.cluster | default "kafka" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace | default "kafka" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        livenessProbe:
          tcpSocket:
            port: 9093
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9093
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: CLUSTER_ID
          value: ZGI1NTk0YmY3NzVjNDk5MD
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: broker,controller
        # TODO(axw) TLS
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://127.0.0.1:9093
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: CONTROLLER
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: 1@127.0.0.1:9094
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
