apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ $.Values.cluster | default "kafka" }}
  namespace: {{ .Values.namespace | default "kafka" }}
spec:
  kafka:
    version: 3.3.2
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {{ .Values.topicOperator | toYaml | nindent 6 }}
    userOperator: {}
