{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.}}
  namespace: {{ $.Values.namespace | default "kafka" }}
  labels:
    strimzi.io/cluster: {{ $.Values.cluster | default "kafka" }}
spec:
  partitions: {{ $.Values.partitions | default 1 }}
  replicas: {{ $.Values.replicas | default 1 }}
{{- end }}
