name: system-test

description: Steps to run system test

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.4.6
      # The permissions for this action are set up
      # at https://github.com/elastic/oblt-infra/blob/main/conf/resources/repos/apm-queue/01-gcp-oidc.tf
    - uses: 'elastic/oblt-actions/google/auth@v1'
    - uses: 'google-github-actions/setup-gcloud@v2'
    - uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'autopilot-oblt'
        location: 'us-central1'
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Test
      working-directory: systemtest
      env:
        KAFKA_NAMESPACE: apm-queue-system-test-gh-workflow-run-${{ github.run_id }}
      run: |
        go test -v -timeout=60m -run-system-tests
      shell: bash
    - name: Cleanup
      if: always() # always run, in case the test step aborts
      working-directory: systemtest
      env:
        KAFKA_NAMESPACE: apm-queue-system-test-gh-workflow-run-${{ github.run_id }}
      run: |
        go test -v -timeout=60m -destroy-only
      shell: bash
