name: system-test

description: Steps to run system test

inputs:
  workload-identity-provider:
    description: 'GCP Workload Identity Provider'
    required: true

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.4.6
    - id: gcp-auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'elastic-observability'
        workload_identity_provider: '${{ inputs.workload-identity-provider }}'
    - uses: 'google-github-actions/setup-gcloud@v2'
    - uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        project_id: ${{ steps.gcp-auth.outputs.project_id }}
        cluster_name: 'autopilot-oblt'
        location: 'us-central1'
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Test
      working-directory: systemtest
      env:
        KAFKA_NAMESPACE: apm-queue-system-test-gh-workflow-run-${{ github.run_id }}
      run: |
        go test -v -timeout=60m -run-system-tests
      shell: bash
    - name: Cleanup
      if: always() # always run, in case the test step aborts
      working-directory: systemtest
      env:
        KAFKA_NAMESPACE: apm-queue-system-test-gh-workflow-run-${{ github.run_id }}
      run: |
        go test -v -timeout=60m -destroy-only
      shell: bash
