name: system-test

description: Steps to run system test

inputs:
  vault-url:
    description: 'Vault URL'
    required: true
  vault-role-id:
      description: 'Vault Role ID'
      required: true
  vault-secret-id:
      description: 'Vault Secret ID'
      required: true

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.4.6
    - uses: hashicorp/vault-action@v2.7.4
      with:
        url: ${{ inputs.vault-url }}
        roleId: ${{ inputs.vault-role-id }}
        secretId: ${{ inputs.vault-secret-id }}
        method: approle
        secrets: |
          secret/observability-team/ci/service-account/apm-queue-system-tests credentials | GOOGLE_CREDS ;
    - id: gcp-auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ env.GOOGLE_CREDS }}'
    - uses: 'google-github-actions/setup-gcloud@v2'
    - uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        project_id: ${{ steps.gcp-auth.outputs.project_id }}
        cluster_name: 'autopilot-oblt'
        location: 'us-central1'
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Test
      working-directory: systemtest
      env:
        GOOGLE_REGION: us-central1
        GOOGLE_PROJECT: ${{ steps.gcp-auth.outputs.project_id }}
        KAFKA_NAMESPACE: apm-queue-system-test-gh-workflow-run-${{ github.run_id }}
        PUBSUBLITE_RESERVATION_PREFIX: systemtest-ci-${{ github.run_id }}
      run: |
        go test -v -timeout=60m -run-system-tests
      shell: bash
    - name: Cleanup
      if: always() # always run, in case the test step aborts
      working-directory: systemtest
      env:
        GOOGLE_REGION: us-central1
        GOOGLE_PROJECT: ${{ steps.gcp-auth.outputs.project_id }}
        KAFKA_NAMESPACE: apm-queue-system-test-gh-workflow-run-${{ github.run_id }}
        PUBSUBLITE_RESERVATION_PREFIX: systemtest-ci-${{ github.run_id }}
      run: |
        go test -v -timeout=60m -destroy-only
      shell: bash
